import { useState, useEffect, useCallback } from 'react';
import { useAuth } from '@/hooks/useAuth';
import {
  createOnboardingCase,
  getUserDraftCase,
  loadCompleteFormData,
  saveBusinessDetails,
  saveOwners,
  saveFinancialInputs,
  saveLoanRequirements,
  saveCompleteFormData,
  submitOnboardingCase,
  uploadDocument,
  deleteDocument,
  getDocuments,
  type OnboardingCase,
  type SaveResult
} from '@/services/onboardingService';
import type { 
  OnboardingFormData, 
  BusinessDetails, 
  OwnerDetails, 
  BankingTurnover, 
  LoanRequirement,
  DocumentUpload
} from '@/types/onboarding.types';
import { createEmptyFormData } from '@/types/onboarding.types';
import { toast } from 'sonner';
import { useDebounce } from './useDebounce';

interface UseOnboardingPersistenceReturn {
  caseId: string | null;
  caseNumber: string | null;
  isLoading: boolean;
  isSaving: boolean;
  lastSaved: Date | null;
  formData: OnboardingFormData;
  initializeCase: () => Promise<string | null>;
  saveStep: (step: number) => Promise<boolean>;
  submitCase: () => Promise<boolean>;
  uploadDoc: (file: File, documentType: string) => Promise<DocumentUpload | null>;
  removeDoc: (documentId: string) => Promise<boolean>;
  updateFormData: (updates: Partial<OnboardingFormData>) => void;
  refreshDocuments: () => Promise<void>;
}

export function useOnboardingPersistence(): UseOnboardingPersistenceReturn {
  const { user } = useAuth();
  const [caseId, setCaseId] = useState<string | null>(null);
  const [caseNumber, setCaseNumber] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [lastSaved, setLastSaved] = useState<Date | null>(null);
  const [formData, setFormData] = useState<OnboardingFormData>(createEmptyFormData());

  // Initialize or load existing draft case
  const initializeCase = useCallback(async (): Promise<string | null> => {
    if (!user) {
      setIsLoading(false);
      return null;
    }

    setIsLoading(true);
    try {
      // Check for existing draft
      const existingCase = await getUserDraftCase();
      
      if (existingCase) {
        setCaseId(existingCase.id);
        setCaseNumber(existingCase.case_number);
        
        // Load form data
        const loadedData = await loadCompleteFormData(existingCase.id);
        if (loadedData) {
          setFormData(loadedData);
        }
        
        setIsLoading(false);
        return existingCase.id;
      }

      // Create new case
      const result = await createOnboardingCase();
      if (result.success && result.caseId) {
        setCaseId(result.caseId);
        // Case number is generated by trigger
        const caseData = await getUserDraftCase();
        if (caseData) {
          setCaseNumber(caseData.case_number);
        }
        setIsLoading(false);
        return result.caseId;
      }

      setIsLoading(false);
      return null;
    } catch (error) {
      console.error('Error initializing case:', error);
      setIsLoading(false);
      return null;
    }
  }, [user]);

  // Save specific step data
  const saveStep = useCallback(async (step: number): Promise<boolean> => {
    if (!caseId) {
      toast.error('No active case to save');
      return false;
    }

    setIsSaving(true);
    let result: SaveResult;

    try {
      switch (step) {
        case 1:
          result = await saveBusinessDetails(caseId, formData.businessDetails);
          break;
        case 2:
          result = await saveOwners(caseId, formData.owners);
          break;
        case 3:
          result = await saveFinancialInputs(caseId, formData.bankingTurnover);
          break;
        case 4:
          result = await saveLoanRequirements(caseId, formData.loanRequirement);
          break;
        case 5:
          // Documents are saved individually during upload
          result = { success: true };
          break;
        case 6:
          // Save everything on review step
          result = await saveCompleteFormData(caseId, formData);
          break;
        default:
          result = { success: true };
      }

      if (result.success) {
        setLastSaved(new Date());
      } else {
        toast.error(result.error || 'Failed to save');
      }

      return result.success;
    } catch (error) {
      console.error('Error saving step:', error);
      toast.error('Failed to save progress');
      return false;
    } finally {
      setIsSaving(false);
    }
  }, [caseId, formData]);

  // Submit the case
  const submitCase = useCallback(async (): Promise<boolean> => {
    if (!caseId) {
      toast.error('No active case to submit');
      return false;
    }

    setIsSaving(true);
    try {
      // Save all data first
      const saveResult = await saveCompleteFormData(caseId, formData);
      if (!saveResult.success) {
        toast.error(saveResult.error || 'Failed to save before submission');
        return false;
      }

      // Submit the case
      const submitResult = await submitOnboardingCase(caseId);
      if (submitResult.success) {
        toast.success('Application submitted successfully!');
        return true;
      } else {
        toast.error(submitResult.error || 'Failed to submit application');
        return false;
      }
    } catch (error) {
      console.error('Error submitting case:', error);
      toast.error('Failed to submit application');
      return false;
    } finally {
      setIsSaving(false);
    }
  }, [caseId, formData]);

  // Upload document
  const uploadDoc = useCallback(async (file: File, documentType: string): Promise<DocumentUpload | null> => {
    if (!caseId) {
      toast.error('No active case for document upload');
      return null;
    }

    const result = await uploadDocument(caseId, file, documentType);
    if (result.success && result.document) {
      setFormData(prev => ({
        ...prev,
        documents: [...prev.documents, result.document!]
      }));
      toast.success('Document uploaded successfully');
      return result.document;
    } else {
      toast.error(result.error || 'Failed to upload document');
      return null;
    }
  }, [caseId]);

  // Remove document
  const removeDoc = useCallback(async (documentId: string): Promise<boolean> => {
    const result = await deleteDocument(documentId);
    if (result.success) {
      setFormData(prev => ({
        ...prev,
        documents: prev.documents.filter(d => d.id !== documentId)
      }));
      toast.success('Document removed');
      return true;
    } else {
      toast.error(result.error || 'Failed to remove document');
      return false;
    }
  }, []);

  // Refresh documents from database
  const refreshDocuments = useCallback(async (): Promise<void> => {
    if (!caseId) return;
    
    const docs = await getDocuments(caseId);
    setFormData(prev => ({
      ...prev,
      documents: docs
    }));
  }, [caseId]);

  // Update form data locally
  const updateFormData = useCallback((updates: Partial<OnboardingFormData>) => {
    setFormData(prev => ({ ...prev, ...updates }));
  }, []);

  // Auto-initialize on mount when user is available
  useEffect(() => {
    if (user && !caseId) {
      initializeCase();
    }
  }, [user, caseId, initializeCase]);

  return {
    caseId,
    caseNumber,
    isLoading,
    isSaving,
    lastSaved,
    formData,
    initializeCase,
    saveStep,
    submitCase,
    uploadDoc,
    removeDoc,
    updateFormData,
    refreshDocuments
  };
}
