-- Add POS eligibility and ABCD fee fields to loan_cases
ALTER TABLE public.loan_cases
ADD COLUMN IF NOT EXISTS vat_turnover NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS adjusted_turnover NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS pos_monthly_turnover NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS pos_annual_turnover NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS pos_cap_adjusted NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS pos_cap_vat NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS pos_eligible_turnover NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS turnover_basis NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS variance_percent NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS eligible_multiplier NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS eligible_loan_amount NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS abcd_fee_rate NUMERIC NOT NULL DEFAULT 0.01,
ADD COLUMN IF NOT EXISTS abcd_fee_amount NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_with_abcd NUMERIC NOT NULL DEFAULT 0;